#!/usr/bin/env bash
# script for running AISG CLI Tool - https://www.aisingapore.org #

# show help message if no input is provided
if [ -z "$1" ]
then
echo "AISG CLI Tool v0.1 - USAGE - aisg module function parameter(s)"
exit 1
fi

# concatenate inputs and pass to execution engine
params="$1"" ""$2"" ""$3"" ""$4"" ""$5"" ""$6"" ""$7"" ""$8"" ""$9"
python -u aisg.py $params
